kind: ConfigMap
apiVersion: v1
metadata:
  name: demo
data:
  application.yml: |-
    application:
      message: Say Hello to the World from Default
    farewell:
      message: Say Goodbye
    ---
    spring:
      profiles: dev
    application:
      message: Say Hello to the Development
    farewell:
      message: Say Goodbye to the Development
    ---
    spring:
      profiles: test
    application:
      message: Say Hello to the Production
